node {
   def mvnHome
   stage('Prepare') {
      git url: 'https://github.com/krishnamurthypradeep/devops-cicd.git', branch: 'master'
      mvnHome = tool 'maven'
   }

    stage('Build') {
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   

        
   stage('Unit Test') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
   stage('Integration Test') {
     if (isUnix()) {
        sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean verify"
     } else {
        bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean verify/)
     }
   }
   stage('Sonar') {
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' sonar:sonar"
      } else {
         bat(/"${mvnHome}\bin\mvn" sonar:sonar/)
      }
   }
        
		
		stage ('Build Docker Image') {
            steps {
                sh 'mvn k8s:build k8s:resource'
            }
        }
		
		stage ('Kubernetes Deploy') {
            steps {
                sh 'mvn k8s:deploy'
            }
        }
    }

